activity/urls.py
from django.urls import path
from .views import Index

app_name = 'activity'
urlpatterns = [
    path('log/save', Index.as_view()),
]

core/urls.py
from django.urls import path
from .views import Index, Show

app_name = 'core'
urlpatterns = [
    path('', Index.as_view()),
    path('wiki/<int:id>', Show.as_view(), name='wiki'),
]

mattermost/urls.py
from django.urls import path
from .views import Api2

urlpatterns = [
    # path('get_user_data/<str:mm_user_id>', Api.as_view()),
    path('v2/get_user_data/<str:mm_user_id>', Api2.as_view()),
]

vaderusermanagement/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

admin.site.site_header = 'DEVOPS CF GUILD' # default: "Django Administration"
admin.site.index_title = 'DEVOPS CF GUILD Administration' # default: "Site administration"
admin.site.site_title = 'DEVOPS CF GUILD Dashboard' # default: "Django site admin"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('api/v1/mattermost/', include('mattermost.urls')),
    path('api/v1/activity/', include('activity.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

activity/models.py
from django.db import models

class Log(models.Model):
    id = models.AutoField(primary_key=True)
    activity = models.TextField()

    def __str__(self):
        return self.activity

core/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Link(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    link = models.CharField(max_length=255)
  
    def __str__(self):
        return self.title

class CfGuildWiki(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    body = RichTextField(blank=True)
    added_at = models.DateField(auto_now_add=True) 
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

mattermost/models.py
from django.db import models
from django.utils import timezone

# class MattermostRole(models.Model):
#     id = models.AutoField(primary_key=True)
#     role_code = models.CharField(max_length=255, null=True)
#     role_name = models.CharField(max_length=255)
#     role_description = models.TextField(null=True)

#     def __str__(self):
#         return self.role_code

class MattermostUser(models.Model):
    id = models.AutoField(primary_key=True)
    mattermost_name = models.CharField(max_length=255)
    mattermost_user_id = models.CharField(max_length=255)
    # role = models.ManyToManyField(MattermostRole)
    group = models.ManyToManyField('MattermostGroup')
    revoke_permission = models.ManyToManyField('MattermostPermission', blank=True)
    added_at = models.DateField(auto_now_add=True) 
    updated_at = models.DateField(auto_now=True) 

    def __str__(self):
        return self.mattermost_user_id

class MattermostPermission(models.Model):
    id = models.AutoField(primary_key=True)
    code = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    group = models.ForeignKey('MattermostGroup', on_delete=models.CASCADE, null=True)
    added_at = models.DateField(default=timezone.now) 
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.code


class MattermostGroup(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    added_at = models.DateField(default=timezone.now) 
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.name

activity/views.py
from django.http import JsonResponse
from django.views import View
from .models import Log
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

import datetime

@method_decorator(csrf_exempt, name='dispatch')
class Index(View):
    
    def post(self, requests):
        action = requests.POST['action'] if 'action' in requests.POST else 'None'
        username = requests.POST['username'] if 'username' in requests.POST else 'None'

        activity_log = "%s performed >>> '%s' <<< on %s" % (username, action, datetime.datetime.now())

        perform = Log(activity=activity_log)
        perform.save()

        return JsonResponse({'status_code': 200, 'message': 'Log successfully saved.'})

core/views.py
from django.views import View
from django.shortcuts import render
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from .models import CfGuildWiki, Link

class Index(View):
    
    template_name = 'index.html'

    def get(self, request, *args, **kwargs):
        # page        = int(request.GET['page']) if 'page' in request.GET else 1
        # search      = request.GET['search'] if 'search' in request.GET else False
        # items       = CfGuildWiki.objects.all().order_by('-id')
        # paginator   = Paginator(items, 10)
        # wikis       = paginator.get_page(page)

        # if search:
        #     items       = CfGuildWiki.objects.filter(title__icontains=str(search)).order_by('title')
        #     paginator   = Paginator(items, 10)
        #     wikis       = paginator.get_page(page)

        # data = {
        #     'items': wikis,
        #     'all_count': paginator.count
        # }
        

        allLinks = Link.objects.all()
        
        context = {
           'allLinks' : allLinks
	    }
 
        return render(request, self.template_name, context)

class Show(View):
    template_name = 'show.html'

    def get(self, request, id):
        item = get_object_or_404(CfGuildWiki, pk=id)

        data = {
            'item': item
        }

        return render(request, self.template_name, data)

mattermost/views.py
#from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
from django.views import View
from .models import MattermostUser, MattermostPermission
import json

# class Api(View):

#     def get(self, request, mm_user_id):
#         user = MattermostUser.objects.filter(mattermost_user_id=mm_user_id)

#         if not user.exists():
#             return JsonResponse({'status_code': 402, 'message': 'Permission denied. User not found or not registered.'})

#         return JsonResponse({'status_code': 200, 'user_data': list(user.values()), 'user_role': list(user[0].role.all().values())})

class Api2(View):
    
    def get(self, request, mm_user_id):
        user = MattermostUser.objects.filter(mattermost_user_id=mm_user_id)

        if not user.exists():
            return JsonResponse({'status_code': 402, 'message': 'Permission denied. User not found or not registered.'})

        groups = user[0].group.all()
        provokes = user[0].revoke_permission.all()
        permission = []
        group_names = []
        grouping = {}

        for g in groups:
            perms = MattermostPermission.objects.filter(group=g.id)
            group_names.append(g.name.lower())
            pr = []
            
            for p in perms:
                permission.append(p.code)
                pr.append(p.code)
                grouping[g.name.lower()] = pr# if len(pr) != 0 else []

        if len(provokes) != 0:
            for pr in provokes:
                if pr.code in permission:
                    permission.remove(pr.code)

                for g in grouping:
                    if pr.code in grouping[g]:
                        grouping[g].remove(pr.code)

        return JsonResponse({'status_code': 200, 'user_data': list(user.values()), 'user_role': permission, 'user_group': group_names , 'grouping': grouping })

core/templates/index.html
{% extends "layouts/base.html" %}
{% load staticfiles %}

{% block title %}ING DEVOPS - CF GUILD WIKI AND MORES{% endblock %}

{% block content %}

<div class ="uk-container">

<form class="uk-search uk-search-large">
    <span uk-search-icon></span>
    <input class="uk-search-input" type="search" placeholder="Search...">

</form>

{% for link in allLinks %}
	<h4 class="uk-heading-bullet">{{ link.title }}</h4>
	<a class="uk-link-text" href="{{ link.link}}">{{ link.link }}</a>
{% endfor %}
</div>

{% endblock %}

core/templates/layouts/base.html
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    {% load staticfiles %}
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    <meta name="generator" content="Codeply">
    <meta name="author" content="CF GUILD / ING DEVOPS">
    <meta property="og:site_name" content="DEVOPS TOOLS" />

    <!-- Less styles -->
    <link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}">
    
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/css/uikit.min.css" />

    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
    {% block styles %}{% endblock %}
</head>
<body>
	{% include 'layouts/includes/header.html' %}

        {% block content %}
            {{ block.super }}
            Welcome
        {% endblock %}
        <!-- The javascript
        ================================================== -->
        <!-- UIkit JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/js/uikit.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/js/uikit-icons.min.js"></script>
        {% block scripts %}{% endblock %}
</body>
</html>

core/templates/layouts/includes/footer.html
{% load staticfiles %}

<div class="pagefooter">
    Copyright @ 2019
</div>

core/templates/layouts/includes/header.html
{% load staticfiles %}

<nav class="uk-navbar-container uk-margin" uk-navbar>
    <div class="uk-navbar-center">

        <div class="uk-navbar-center-left">
	</div>
	<a class="uk-navbar-item uk-logo" href="#"><img src={% static 'img/devops-process.png' %} height="80" width="80"></a>
	<p class="uk-text-large uk-text-lead">DevOps Wiki</p>
        <div class="uk-navbar-center-right"></div>

    </div>
</nav>

core/templates/layouts/includes/sidebar.html
{% load staticfiles %}
<div class="sidebar">
    <div class="logo">
        <a href="/"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
    </div>
    <div class="navigation">
        <h3>Wiki List</h3>
        <ul>
            {% if 'wiki'|sidebar|len != 0 %}
                {% for i in 'site'|sidebar %}
                <li><a href="{% url 'core:wiki' i.id %}">{{i.title}}</a></li>
                {% endfor %}
            {% else %}
            <li><a href="#">No Wiki Yet</a></li>
            {% endif %}
        </ul>
    </div>
</div>

core/templates/show.html
{% extends "layouts/base.html" %}
{% load staticfiles %}

{% block title %}ING DEVOPS - CF GUILD WIKI AND MORE{% endblock %}

{% block content %}
<div class="article">
    <h1>{{item.title}}</h1>
    <p class="siteSub">Published on {{item.added_at}} and Last Updated on {{item.updated_at}}</p>

    {{item.body|safe}}
</div>
{% endblock %}